// <auto-generated />
using System;
using AuthenticationServer.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthenticationServer.API.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    [Migration("20221019061148_AddIsAgreeToTermsOfServiceVersion")]
    partial class AddIsAgreeToTermsOfServiceVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthenticationServer.API.Entities.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(19)")
                        .HasColumnName("member_id");

                    b.Property<int?>("Age")
                        .HasColumnType("int(10)")
                        .HasColumnName("age");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gender");

                    b.Property<string>("Nickname")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("member");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(4923), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail1@google.com",
                            Gender = "MALE",
                            Nickname = "김성재",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5031), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail2@google.com",
                            Gender = "FEMALE",
                            Nickname = "이진석",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5036), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail3@google.com",
                            Gender = "MALE",
                            Nickname = "김한별",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5040), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail4@google.com",
                            Gender = "FEMALE",
                            Nickname = "박저스틴",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5043), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail5@google.com",
                            Gender = "FEMALE",
                            Nickname = "최한별",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername5"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5058), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail6@google.com",
                            Gender = "MALE",
                            Nickname = "한한별",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername6"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5061), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail7@google.com",
                            Gender = "FEMALE",
                            Nickname = "최두훈",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername7"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5063), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail8@google.com",
                            Gender = "MALE",
                            Nickname = "이한별",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername8"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5065), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail9@google.com",
                            Gender = "MALE",
                            Nickname = "이두훈",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername9"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 10, 19, 6, 11, 48, 625, DateTimeKind.Unspecified).AddTicks(5068), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "seedMail10@google.com",
                            Gender = "MALE",
                            Nickname = "김저스틴",
                            Password = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            Role = "ROLE_USER",
                            UserName = "seedUsername10"
                        });
                });

            modelBuilder.Entity("AuthenticationServer.API.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("AuthenticationServer.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsAgreeToTermsOfServiceVersion")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint(19)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c6f8f53-8f99-4fac-8f8b-bddf37d9db6d",
                            Email = "seedMail1@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 1L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername1"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d496ad8c-4a8b-4414-ae2e-92db04eab255",
                            Email = "seedMail2@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 2L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername2"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2d22ca0-260b-4b88-ac7a-6fabe3439059",
                            Email = "seedMail3@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 3L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername3"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "551d1011-8c1f-4573-9cb4-0dcef9fe37a3",
                            Email = "seedMail4@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 4L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername4"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "97f298cd-622d-4788-b06a-3dc4aae48829",
                            Email = "seedMail5@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 5L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername5"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e1f541b-de3f-4c1f-94bf-9fa4fafadbfb",
                            Email = "seedMail6@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 6L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername6"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52e8445a-74b3-4200-bb8b-3420f1bcafae",
                            Email = "seedMail7@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 7L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername7"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0970ee4e-fff1-4100-9a8d-6ff932000276",
                            Email = "seedMail8@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 8L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername8"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "298c9d1b-ee0e-46db-81c1-39878e853cbe",
                            Email = "seedMail9@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 9L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername9"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0af0473e-7cc7-40b1-b56c-1b9bb9d9d038",
                            Email = "seedMail10@google.com",
                            EmailConfirmed = false,
                            IsAgreeToTermsOfServiceVersion = 1,
                            LockoutEnabled = false,
                            MemberId = 10L,
                            PasswordHash = "$2a$11$5hR4FzsKur9m2yCMSCTF6.IFFeTM4KmW7fywgzN4R8BT6quA88VEG",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "seedUsername10"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AuthenticationServer.API.Entities.User", b =>
                {
                    b.HasOne("AuthenticationServer.API.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AuthenticationServer.API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AuthenticationServer.API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthenticationServer.API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AuthenticationServer.API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
